import 'package:flutter/material.dart';
import '../models/website_data.dart';

class CustomNavigationDrawer extends StatelessWidget {
  final WebsiteData websiteData;

  const CustomNavigationDrawer({super.key, required this.websiteData});

  @override
  Widget build(BuildContext context) {
    return Drawer(
      child: Column(
        children: [
          DrawerHeader(
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [
                  Theme.of(context).primaryColor,
                  Theme.of(context).primaryColor.withOpacity(0.7),
                ],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisAlignment: MainAxisAlignment.end,
              children: [
                const Icon(
                  Icons.web,
                  size: 48,
                  color: Colors.white,
                ),
                const SizedBox(height: 8),
                Text(
                  websiteData.domain,
                  style: const TextStyle(
                    color: Colors.white,
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                Text(
                  '${websiteData.pages.length} pages • ${websiteData.assets.length} assets',
                  style: const TextStyle(
                    color: Colors.white70,
                    fontSize: 12,
                  ),
                ),
              ],
            ),
          ),
          Expanded(
            child: ListView(
              padding: EdgeInsets.zero,
              children: [
                ListTile(
                  leading: const Icon(Icons.home),
                  title: const Text('Home'),
                  onTap: () {
                    Navigator.pop(context);
                    Navigator.pushReplacementNamed(context, '/');
                  },
                ),
                const Divider(),
                ListTile(
                  leading: const Icon(Icons.pages),
                  title: const Text('All Pages'),
                  subtitle: Text('${websiteData.pages.length} pages'),
                  onTap: () {
                    Navigator.pop(context);
                    // Navigate to pages list
                  },
                ),
                ListTile(
                  leading: const Icon(Icons.image),
                  title: const Text('Assets'),
                  subtitle: Text('${websiteData.assets.length} assets'),
                  onTap: () {
                    Navigator.pop(context);
                    // Navigate to assets list
                  },
                ),
                const Divider(),
                ListTile(
                  leading: const Icon(Icons.info),
                  title: const Text('About'),
                  onTap: () {
                    Navigator.pop(context);
                    _showAboutDialog(context);
                  },
                ),
                ListTile(
                  leading: const Icon(Icons.refresh),
                  title: const Text('Refresh Data'),
                  onTap: () {
                    Navigator.pop(context);
                    // Trigger data refresh
                  },
                ),
              ],
            ),
          ),
          const Divider(),
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              children: [
                Text(
                  'Generated by Eddie',
                  style: Theme.of(context).textTheme.bodySmall,
                ),
                Text(
                  'Website to Flutter App Generator',
                  style: Theme.of(context).textTheme.bodySmall?.copyWith(
                    color: Colors.grey,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  void _showAboutDialog(BuildContext context) {
    showAboutDialog(
      context: context,
      applicationName: 'Website App',
      applicationVersion: '1.0.0',
      applicationIcon: const Icon(Icons.web, size: 48),
      children: [
        const Text('This app was generated from website data using Eddie.'),
        const SizedBox(height: 16),
        Text('Original Website: ${websiteData.originalUrl}'),
        Text('Domain: ${websiteData.domain}'),
        Text('Crawled: ${_formatDate(websiteData.crawledAt)}'),
        Text('Pages: ${websiteData.pages.length}'),
        Text('Assets: ${websiteData.assets.length}'),
      ],
    );
  }

  String _formatDate(DateTime date) {
    return '${date.day}/${date.month}/${date.year} at ${date.hour}:${date.minute.toString().padLeft(2, '0')}';
  }
}
